#!/usr/bin/env python3
"""Inventory observable Stage-C rule candidates without changing curation output."""
from __future__ import annotations

import argparse
import ast
import json
import re
import warnings
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


JsonMap = dict[str, Any]
GENERATED_MARKER_RE = re.compile(
    r"\b(?:auto[- ]?generated|automatically generated|generated by|code generated|do not edit)\b",
    re.IGNORECASE,
)
STRONG_GENERATED_MARKER_RE = re.compile(
    r"^\s*(?:[#/;*\-]+\s*)?(?:\b(?:generated by|auto[- ]?generated|automatically generated)\b[^\n]{0,160}\bdo not edit\b|\bdo not edit\b[^\n]{0,160}\b(?:generated by|auto[- ]?generated|automatically generated)\b)",
    re.IGNORECASE | re.MULTILINE,
)
PATH_RULES = {
    "vendored_dependency_path_candidate": re.compile(r"(?:^|/)(?:vendor|third_party|node_modules|site-packages|dist-packages)(?:/|$)", re.IGNORECASE),
    "generated_path_candidate": re.compile(r"(?:^|/)(?:generated|autogen|auto_generated)(?:/|$)", re.IGNORECASE),
    "minified_asset_path_candidate": re.compile(r"\.min\.(?:js|css)$", re.IGNORECASE),
    "lockfile_path_candidate": re.compile(r"(?:^|/)(?:package-lock\.json|poetry\.lock|pdm\.lock|yarn\.lock|composer\.lock|cargo\.lock)$", re.IGNORECASE),
}
CODE_CUE_RE = re.compile(r"^\s*(?:def |class |async def |from |import |@|if __name__|function |const |let |var )", re.MULTILINE)


def _read_jsonl(path: Path) -> Iterable[JsonMap]:
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                yield json.loads(line)


def _normalized_nonempty_lines(text: str) -> list[str]:
    return [" ".join(line.split()) for line in text.splitlines() if line.strip()]


def _python_parse_status(text: str) -> str:
    if not CODE_CUE_RE.search(text) or "```" in text:
        return "not_applicable"
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", SyntaxWarning)
            ast.parse(text)
    except SyntaxError:
        return "syntax_error"
    return "parseable"


def _evidence(text: str, policy_metadata: JsonMap) -> dict[str, Any]:
    lines = _normalized_nonempty_lines(text)
    line_counts = Counter(lines)
    nonempty_count = len(lines)
    max_line_length = max((len(line) for line in lines), default=0)
    repeated_fraction = max(line_counts.values(), default=0) / max(1, nonempty_count)
    path = str(policy_metadata.get("path") or "")
    return {
        "generated_marker": bool(GENERATED_MARKER_RE.search(text)),
        "strong_generated_marker_candidate": bool(STRONG_GENERATED_MARKER_RE.search(text)),
        "one_or_two_line_minified_candidate": nonempty_count <= 2 and max_line_length >= 1000,
        "pathological_line_repetition_candidate": nonempty_count >= 12 and repeated_fraction >= 0.75,
        "license_or_comment_only_candidate": bool(lines) and all(line.startswith(("#", "//", "/*", "*", "<!--")) for line in lines),
        "python_parse_status": _python_parse_status(text),
        "nonempty_lines": nonempty_count,
        "max_normalized_line_chars": max_line_length,
        "max_repeated_line_fraction": round(repeated_fraction, 6),
        **{name: bool(pattern.search(path)) for name, pattern in PATH_RULES.items()},
    }


def build_inventory(rows: Iterable[JsonMap], sample_limit: int) -> JsonMap:
    candidate_keys = (
        "generated_marker",
        "strong_generated_marker_candidate",
        "one_or_two_line_minified_candidate",
        "pathological_line_repetition_candidate",
        "license_or_comment_only_candidate",
        *PATH_RULES,
    )
    counts: Counter[str] = Counter()
    parse_statuses: Counter[str] = Counter()
    samples: dict[str, list[JsonMap]] = {key: [] for key in candidate_keys}
    total = 0
    for row in rows:
        total += 1
        policy_metadata = row.get("stage_c_policy_metadata") if isinstance(row.get("stage_c_policy_metadata"), dict) else {}
        evidence = _evidence(str(row["text"]), policy_metadata)
        parse_statuses[evidence["python_parse_status"]] += 1
        for key in candidate_keys:
            if not evidence[key]:
                continue
            counts[key] += 1
            if len(samples[key]) < sample_limit:
                samples[key].append(
                    {
                        "chunk_uid": row["chunk_uid"],
                        "stage_a_record_id": row.get("stage_a_record_id"),
                        "policy_metadata": policy_metadata,
                        "evidence": {name: evidence[name] for name in evidence if name != "generated_marker" or key == name},
                    }
                )
    return {
        "schema_version": "core-rule-candidate-inventory-v1",
        "status": "diagnostic_only_not_a_selection_policy",
        "scope": "Observable text-only candidates. Counts do not authorize removal until each candidate has a false-positive audit and an explicit policy contract.",
        "total_chunks": total,
        "candidate_counts": dict(counts),
        "python_parseability_diagnostic": dict(parse_statuses),
        "candidate_samples": samples,
        "candidate_definitions": {
            "generated_marker": "Contains an explicit generated-content marker.",
            "strong_generated_marker_candidate": "Contains both a generated-content marker and an explicit do-not-edit instruction.",
            "one_or_two_line_minified_candidate": "At most two nonempty lines and a normalized line at least 1000 characters long.",
            "pathological_line_repetition_candidate": "At least 12 nonempty lines and one normalized line occupies at least 75% of them.",
            "license_or_comment_only_candidate": "Every nonempty line is a comment-like line.",
            "python_parse_status": "Diagnostic only; chunking can introduce syntax errors, so it is not a removal rule.",
            **{name: "Matches a declared relative-path artifact pattern; diagnostic only." for name in PATH_RULES},
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a diagnostic inventory for potential Core rules.")
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--sample-limit", type=int, default=10)
    args = parser.parse_args()
    if args.sample_limit < 1:
        raise RuntimeError("sample-limit must be positive")
    report = build_inventory(_read_jsonl(args.input), args.sample_limit)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"status": report["status"], "total_chunks": report["total_chunks"], "candidate_counts": report["candidate_counts"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
