#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["transformers"]
# ///
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from collections import defaultdict
from collections.abc import Callable
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Final, TypeAlias


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from code_positive_evidence import inspect_python_complete_source


JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]
TokenCounter: TypeAlias = Callable[[str], int]
EXCLUDED_PARTS: Final = frozenset(
    {".git", ".venv", "venv", "build", "dist", "__pycache__", "site-packages", "node_modules", "vendor", "vendored"}
)
GENERATED_MARKERS: Final = ("generated file", "auto-generated", "autogenerated")


@dataclass(frozen=True, slots=True)
class ControlBuildError(RuntimeError):
    detail: str

    def __str__(self) -> str:
        return self.detail


@dataclass(frozen=True, slots=True)
class RepoSpec:
    source_group: str
    root: Path
    commit: str


def _normalized(text: str) -> str:
    return " ".join(text.split())


def _generated(text: str) -> bool:
    prefix = text[:2000].casefold()
    return "do not edit" in prefix and any(marker in prefix for marker in GENERATED_MARKERS)


def _excluded_path(path: Path, root: Path) -> bool:
    return bool({part.casefold() for part in path.relative_to(root).parts} & EXCLUDED_PARTS)


def build_control_records(
    repositories: tuple[RepoSpec, ...],
    candidate_normalized_texts: frozenset[str],
    token_counter: TokenCounter,
) -> tuple[list[dict[str, JsonValue]], dict[str, int]]:
    """Build source-time-disjoint controls using structural gates fixed before scoring."""
    rows: list[dict[str, JsonValue]] = []
    counts: dict[str, int] = defaultdict(int)
    seen_normalized: dict[str, str] = {}
    for repository in repositories:
        for path in sorted(repository.root.rglob("*.py")):
            if _excluded_path(path, repository.root):
                continue
            counts["python_files_seen"] += 1
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                counts["utf8_decode_excluded"] += 1
                continue
            if _generated(text):
                counts["generated_marker_excluded"] += 1
                continue
            structural = inspect_python_complete_source(text, "python", "source_row", "complete_source")
            if structural.coherence_completeness == 0.0:
                counts["parse_failed_excluded"] += 1
                continue
            if structural.substantive_payload == 0.0:
                counts["non_substantive_excluded"] += 1
                continue
            normalized = _normalized(text)
            if normalized in candidate_normalized_texts:
                counts["candidate_hash_overlap_excluded"] += 1
                continue
            previous_source = seen_normalized.get(normalized)
            if previous_source is not None:
                counts["cross_repository_duplicate_excluded"] += 1
                continue
            seen_normalized[normalized] = repository.source_group
            relative = path.relative_to(repository.root).as_posix()
            rows.append(
                {
                    "record_id": f"{repository.source_group}::{relative}",
                    "text": text,
                    "token_count": token_counter(text),
                    "normalized_text_sha256": hashlib.sha256(normalized.encode("utf-8")).hexdigest(),
                    "language": {"code": "python", "confidence": 1.0, "declaration": "source_row"},
                    "record_shape": "complete_source",
                    "source_group": repository.source_group,
                    "source_commit": repository.commit,
                }
            )
            counts["retained"] += 1
    return rows, dict(counts)


def _git_head(root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def main() -> int:
    parser = argparse.ArgumentParser(description="Build post-Stack-v2 Python clean controls.")
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--candidate", type=Path, required=True)
    parser.add_argument("--tokenizer", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()

    config = json.loads(args.config.read_text(encoding="utf-8"))
    repositories: list[RepoSpec] = []
    for raw in config["repositories"]:
        source_group = str(raw["source_group"])
        root = args.repo_root / source_group.rsplit("/", 1)[-1]
        expected_commit = str(raw["commit"])
        actual_commit = _git_head(root)
        if actual_commit != expected_commit:
            raise ControlBuildError(f"Commit mismatch for {source_group}: {actual_commit}")
        repositories.append(RepoSpec(source_group, root, expected_commit))

    candidate_normalized: set[str] = set()
    with args.candidate.open(encoding="utf-8") as source:
        for line in source:
            raw = json.loads(line)
            text = raw.get("text")
            if isinstance(text, str):
                candidate_normalized.add(_normalized(text))

    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer, local_files_only=True)
    rows, counts = build_control_records(
        tuple(repositories),
        frozenset(candidate_normalized),
        lambda text: len(tokenizer.encode(text, add_special_tokens=False)),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as target:
        for row in rows:
            target.write(json.dumps(row, ensure_ascii=False) + "\n")
    report = {
        "schema_version": "post-stack-v2-python-clean-control-report-v1",
        "status": "materialized_before_provider_scoring",
        "repositories": [asdict(repository) | {"root": str(repository.root)} for repository in repositories],
        "counts": counts,
        "tokens": sum(int(row["token_count"]) for row in rows),
        "target_retention_fraction_used": False,
        "external_results_visible": False,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps({"status": report["status"], "records": len(rows), "tokens": report["tokens"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
