#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def main() -> int:
    from scripts.build_core_rule_inventory import build_inventory

    rows = [
        {"chunk_uid": "generated", "text": "// Code generated by tool. DO NOT EDIT.", "stage_c_policy_metadata": {"path": "generated/model.py"}},
        {"chunk_uid": "minified", "text": "x" * 1001, "stage_c_policy_metadata": {"path": "dist/app.min.js"}},
        {"chunk_uid": "repeat", "text": "value = source\n" * 12},
        {"chunk_uid": "comment", "text": "# license\n# terms"},
        {"chunk_uid": "code", "text": "def add(left, right):\n    return left + right\n"},
    ]
    report = build_inventory(rows, sample_limit=2)
    assert report["total_chunks"] == 5
    assert report["candidate_counts"] == {
        "generated_marker": 1,
        "strong_generated_marker_candidate": 1,
        "one_or_two_line_minified_candidate": 1,
        "pathological_line_repetition_candidate": 1,
        "license_or_comment_only_candidate": 2,
        "generated_path_candidate": 1,
        "minified_asset_path_candidate": 1,
    }
    assert report["python_parseability_diagnostic"]["parseable"] == 1
    print("[core-rule-inventory] observable candidate accounting: pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
