#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def main() -> int:
    from stage_c_selection import select_chunks

    base = " ".join(f"token{index}" for index in range(100))
    chunks = [
        {"chunk_uid": "a-representative", "text": base},
        {"chunk_uid": "z-near-copy", "text": base.replace("token99", "replacement")},
        {
            "chunk_uid": "shared-phrase-only",
            "text": "This function computes a deterministic total without mutating its input but the surrounding parser validates incoming dates converts time zones serializes JSON responses records audit events handles invalid request payloads and returns diagnostic metadata for a separate service boundary with independent retry behavior.",
        },
        {
            "chunk_uid": "a-scaffold",
            "text": "# package exports\nfrom package.alpha import Alpha\nfrom package.beta import Beta\nfrom package.gamma import Gamma\nfrom package.delta import Delta\nfrom package.epsilon import Epsilon\n__all__ = ['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon']",
        },
        {
            "chunk_uid": "z-scaffold",
            "text": "# equivalent package export scaffold\nfrom package.alpha import Alpha\nfrom package.beta import Beta\nfrom package.gamma import Gamma\nfrom package.delta import Delta\nfrom package.epsilon import Epsilon\n__all__ = ['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon']",
        },
        {
            "chunk_uid": "distinct-scaffold",
            "text": "# different module exports\nfrom module.orange import Orange\nfrom module.purple import Purple\nfrom module.silver import Silver\nfrom module.green import Green\nfrom module.yellow import Yellow\n__all__ = ['Orange', 'Purple', 'Silver', 'Green', 'Yellow']",
        },
    ]
    selected, not_selected, audit = select_chunks(chunks, {})
    assert {chunk["chunk_uid"] for chunk in selected} == {
        "a-representative",
        "z-near-copy",
        "shared-phrase-only",
        "a-scaffold",
        "distinct-scaffold",
    }
    assert {chunk["chunk_uid"] for chunk in not_selected} == {"z-scaffold"}
    assert {chunk["stage_c_selection"]["removed_reason"] for chunk in not_selected} == {
        "structural_scaffold_representative_retained",
    }
    assert audit["selection_mode"] == "reason_coded_duplicate_and_scaffold_compaction_without_budget"
    assert audit["near_duplicate_removed_chunks"] == 0
    assert audit["structural_scaffold_removed_chunks"] == 1
    assert audit["coverage_representatives_retained"] == 1
    assert audit["budget_applied"] is False
    assert audit["utility_read"] is False
    assert audit["benchmark_outcomes_read"] is False
    scaffold_removed = next(chunk for chunk in not_selected if chunk["chunk_uid"] == "z-scaffold")
    assert scaffold_removed["stage_c_selection"]["representative_chunk_uid"] == "a-scaffold"
    assert scaffold_removed["stage_c_selection"]["token_delta_proxy"] < 0
    assert next(chunk for chunk in selected if chunk["chunk_uid"] == "z-near-copy")["stage_c_selection"][
        "accepted_by"
    ] == "no_symmetric_near_duplicate_match"

    generated_chunks = [
        {
            "chunk_uid": "generated-file::0000",
            "stage_a_record_id": "generated-file",
            "stage_c_policy_metadata": {"language_code": "python", "content_type": "code"},
            "text": "# Generated by schema compiler. DO NOT EDIT.\nclass Message:\n    pass\n",
        },
        {
            "chunk_uid": "generated-file::0001",
            "stage_a_record_id": "generated-file",
            "stage_c_policy_metadata": {"language_code": "python", "content_type": "code"},
            "text": "def serialize(message):\n    return message.encode()\n",
        },
        {
            "chunk_uid": "authored-file::0000",
            "stage_a_record_id": "authored-file",
            "stage_c_policy_metadata": {"language_code": "javascript", "content_type": "code"},
            "text": "def normalize(value):\n    return value.strip().lower()\n",
        },
    ]
    generated_selected, generated_removed, generated_audit = select_chunks(
        generated_chunks,
        {"structural_artifact_rules": {"explicit_generated_artifact": True}},
    )
    assert {chunk["chunk_uid"] for chunk in generated_selected} == {"authored-file::0000"}
    assert {chunk["chunk_uid"] for chunk in generated_removed} == {"generated-file::0000", "generated-file::0001"}
    assert {chunk["stage_c_selection"]["removed_reason"] for chunk in generated_removed} == {"explicit_generated_artifact"}
    assert {chunk["quality_retention_decision"]["decision"] for chunk in generated_removed} == {"reject"}
    assert all(
        chunk["quality_retention_decision"]["policy_artifact_sha256"]
        and chunk["quality_retention_decision"]["observed_evidence"]
        for chunk in generated_removed
    )
    assert generated_selected[0]["quality_retention_decision"]["decision"] == "abstain_retain"
    assert generated_audit["explicit_generated_artifact_removed_chunks"] == 2
    assert generated_audit["quality_retention"]["decision_counts"] == {
        "reject": 2,
        "keep": 0,
        "abstain_retain": 1,
    }

    license_chunks = [
        {
            "chunk_uid": "license-only",
            "stage_c_policy_metadata": {"language_code": "python", "content_type": "code"},
            "text": "# Copyright 2025 Fixture Authors\n# SPDX-License-Identifier: Apache-2.0\n",
        },
        {
            "chunk_uid": "ordinary-comment",
            "stage_c_policy_metadata": {"language_code": "python", "content_type": "code"},
            "text": "# This comment explains why the parser rejects malformed input.\ndef parse(value):\n    return value.strip()\n",
        },
        {
            "chunk_uid": "non-code-license",
            "stage_c_policy_metadata": {"language_code": "english", "content_type": "general"},
            "text": "# Copyright 2025 Fixture Authors\n# SPDX-License-Identifier: Apache-2.0\n",
        },
    ]
    license_selected, license_removed, license_audit = select_chunks(
        license_chunks,
        {"structural_artifact_rules": {"license_comment_only_chunk": True}},
    )
    assert {chunk["chunk_uid"] for chunk in license_selected} == {"ordinary-comment"}
    assert {chunk["chunk_uid"] for chunk in license_removed} == {"license-only", "non-code-license"}
    assert {chunk["stage_c_selection"]["removed_reason"] for chunk in license_removed} == {"license_comment_only_chunk"}
    assert license_audit["license_comment_only_removed_chunks"] == 2

    try:
        select_chunks(
        generated_chunks,
        {
            "structural_artifact_rules": {"explicit_generated_artifact": True},
            "coverage_guard": {"strata": ["language_code", "content_type"]},
        },
        )
    except RuntimeError as error:
        assert "audit-only" in str(error)
    else:
        raise AssertionError("Coverage must not retain metadata strata or alter selection.")

    try:
        select_chunks(chunks, {"operational_selection": {"minimum_priority_score": 0.5}})
    except RuntimeError as error:
        assert "retired" in str(error)
    else:
        raise AssertionError("Retired weighted operational selection must be rejected.")

    print("[stage-c-selection] reason-coded duplicate, generated-artifact, and scaffold compaction: pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
