#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))


def row(
    chunk_uid: str,
    text: str,
    *,
    token_proxy: int,
    hard_gate: bool = False,
) -> dict[str, object]:
    return {
        "chunk_uid": chunk_uid,
        "text": text,
        "token_proxy": token_proxy,
        "stage_b_hard_gate_reasons": ["text_too_short"] if hard_gate else [],
        "stage_c_policy_metadata": {"path": "src/example.py"},
        "stage_b_selection": {
            "operational_priority": {
                "length_support": 0.4,
                "structural_richness": 0.5,
                "lexical_or_identifier_diversity": 0.6,
                "pass_through_assignment_ratio": 0.0,
                "score": 0.7,
            }
        },
    }


def main() -> int:
    from build_historical_selector_decomposition import build_report

    selected = [row("kept", "def add(left, right):\n    return left + right\n", token_proxy=12)]
    rejected = [
        row("hard-gate", "x", token_proxy=1, hard_gate=True),
        row("license", "# copyright\n# license", token_proxy=4),
        row("generated", "# Generated by tool. DO NOT EDIT.", token_proxy=6),
        row("minified", "x" * 1001, token_proxy=20),
        row("partial", "def incomplete(", token_proxy=8),
        row("proxy-only", "def forward(value):\n    return value\n", token_proxy=9),
    ]

    report = build_report(selected, rejected)
    rejected_families = report["groups"]["historical_rejected"]["families"]
    assert rejected_families["hard_gate_rejection"] == {"chunks": 1, "token_proxy": 1}
    assert rejected_families["explicit_license_comment_only_candidate"] == {"chunks": 1, "token_proxy": 4}
    assert rejected_families["explicit_generated_do_not_edit_candidate"] == {"chunks": 1, "token_proxy": 6}
    assert rejected_families["minified_shape_candidate"] == {"chunks": 1, "token_proxy": 20}
    assert rejected_families["partial_or_unparseable_chunk_diagnostic"] == {"chunks": 1, "token_proxy": 8}
    assert rejected_families["proxy_only_no_explicit_evidence"] == {"chunks": 1, "token_proxy": 9}
    assert report["groups"]["historical_selected"]["families"]["proxy_only_no_explicit_evidence"] == {
        "chunks": 1,
        "token_proxy": 12,
    }
    print("[historical-selector-decomposition] explicit evidence remains distinct from proxy-only exclusions: pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
