#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

from build_rule_opportunity_audit import build_report


def row(text: str, **kwargs: object) -> dict[str, object]:
    artifact_context = kwargs.get("artifact_context") if isinstance(kwargs.get("artifact_context"), dict) else {}
    return {
        "text": text,
        "token_count": 7,
        "audit_only_metadata": {"provenance": {"source_name": "fixture", "license": "MIT"}},
        "partition": {"path": kwargs.get("path", "src/example.py"), "content_type": "code", "source_tier": "raw_like"},
        "stage_c_policy_metadata": {
            "path": kwargs.get("path", "src/example.py"),
            "content_type": "code",
            **({"declared_generation": artifact_context["generation"]} if "generation" in artifact_context else {}),
            **({"declared_dependency_copy": artifact_context["dependency_copy"]} if "dependency_copy" in artifact_context else {}),
        },
    }


def main() -> int:
    report = build_report(
        [
            row("def useful():\n    return 1\n"),
            row("# generated by tool\n# do not edit\n", artifact_context={"generation": "generated"}),
            row("def dependency():\n    return 2\n", path="vendor/library.py", artifact_context={"dependency_copy": True}),
        ]
    )
    assert report["corpus"] == {"chunks": 3, "token_proxy": 21}
    assert report["metadata_availability"]["present_chunks"]["path"] == 3
    assert report["metadata_availability"]["declared_value_counts"]["artifact_context.generation"] == {"generated": 1}
    assert report["rule_assessment"]["declared_generated_artifact"]["status"] == "needs_executable_false_positive_fixture"
    assert report["rule_assessment"]["declared_dependency_copy"]["status"] == "needs_executable_false_positive_fixture"
    assert report["rule_assessment"]["path_based_vendor_or_generated"]["status"] == "blocked_known_false_positive_risk"

    canonical_stage_a_report = build_report(
        [
            {
                "text": "# generated source\nVALUE = 1\n",
                "token_count": 5,
                "artifact_context": {"generation": "generated"},
                "partition": {"path": "generated.py", "content_type": "code"},
            }
        ]
    )
    assert canonical_stage_a_report["rule_assessment"]["declared_generated_artifact"] == {
        "evidence": "artifact_context.generation=generated",
        "candidates": 1,
        "status": "needs_executable_false_positive_fixture",
    }
    print("[rule-opportunity-audit] provenance and false-positive boundary fixture: pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
