#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from quality_retention import (
    QualityRetentionContractError,
    QualityRetentionDecision,
    RoutingPreconditionTrace,
    evaluate_quality_retention,
)


def _row(chunk_uid: str, text: str, record_id: str | None = None) -> dict[str, object]:
    return {
        "chunk_uid": chunk_uid,
        "stage_a_record_id": record_id or chunk_uid,
        "text": text,
        "token_proxy": len(text.split()),
    }


def main() -> int:
    rows = [
        _row("generated::0", "# Generated by schema compiler. DO NOT EDIT.", "generated"),
        _row("generated::1", "class Message:\n    pass", "generated"),
        _row("license", "# Copyright 2026 Authors\n# SPDX-License-Identifier: Apache-2.0"),
        _row("empty-html", "<!doctype html><html><head></head><body></body></html>"),
        _row(
            "web-chrome",
            "Cookie preferences\nAccept all\nReject all\nManage preferences\nPrivacy policy\nTerms of service",
        ),
        _row("substantive", "A proof explains why the derivative of a sum is the sum of derivatives."),
    ]
    settings = {
        "explicit_generated_artifact": True,
        "license_comment_only_chunk": True,
        "empty_html_shell": True,
        "web_chrome_only_chunk": True,
    }

    decisions, audit = evaluate_quality_retention(rows, settings)

    assert decisions["generated::0"]["decision"] == "reject"
    assert decisions["generated::1"]["reason_code"] == "explicit_generated_artifact"
    assert decisions["license"]["reason_code"] == "license_comment_only_chunk"
    assert decisions["empty-html"]["reason_code"] == "empty_html_shell"
    assert decisions["web-chrome"]["reason_code"] == "explicit_web_chrome_only_chunk"
    assert decisions["substantive"]["decision"] == "abstain_retain"
    assert decisions["substantive"]["intrinsic_quality_claim"] is False
    required_reject_fields = {
        "schema_version",
        "chunk_uid",
        "policy_scope_route",
        "routing_precondition",
        "policy_id",
        "policy_version",
        "reason_code",
        "trigger",
        "observed_evidence",
        "representative_fixture_id",
        "false_positive_fixture_id",
        "original_text_sha256",
        "policy_artifact_sha256",
        "token_delta_proxy",
    }
    for decision in decisions.values():
        if decision["decision"] == "reject":
            assert required_reject_fields <= set(decision)
            assert decision["policy_scope_route"] == "common_all_routes"
            assert len(decision["original_text_sha256"]) == 64
            assert len(decision["policy_artifact_sha256"]) == 64
            assert decision["token_delta_proxy"] < 0
            assert decision["observed_evidence"]
            fixture_path = ROOT / decision["representative_fixture_id"].split("#", 1)[0]
            fixture_ids = {
                case["id"]
                for case in json.loads(fixture_path.read_text(encoding="utf-8"))["cases"]
            }
            assert decision["representative_fixture_id"].split("#", 1)[1] in fixture_ids
            assert decision["false_positive_fixture_id"].split("#", 1)[1] in fixture_ids
    assert audit["decision_counts"] == {"reject": 5, "keep": 0, "abstain_retain": 1}
    assert audit["weighted_score_used"] is False
    assert audit["benchmark_outcomes_read"] is False

    disabled, disabled_audit = evaluate_quality_retention([rows[-1]], {})
    assert disabled["substantive"]["decision"] == "abstain_retain"
    assert disabled["substantive"]["evaluated_policy_ids"] == []
    assert disabled_audit["decision_counts"]["abstain_retain"] == 1

    candidate_rows = [
        _row("error-nav", "404 Page Not Found\nHome\nAbout\nContact\nSearch"),
        _row(
            "url-directory",
            "https://example.com/a\nhttps://example.com/b\nhttps://example.com/c\nhttps://example.com/d\nhttps://example.com/e",
        ),
        _row(
            "error-explanation",
            "This guide explains why a reverse proxy returns 404 Page Not Found and how routing fixes the error.",
        ),
        _row(
            "annotated-references",
            "Parser reference: https://example.com/parser\nRuntime reference: https://example.com/runtime",
        ),
    ]
    candidate_decisions, candidate_audit = evaluate_quality_retention(
        candidate_rows,
        {
            "explicit_error_navigation_only_chunk_candidate": True,
            "url_directory_only_chunk_candidate": True,
        },
    )
    assert candidate_decisions["error-nav"]["reason_code"] == "explicit_error_navigation_only_chunk"
    assert candidate_decisions["url-directory"]["reason_code"] == "url_directory_only_chunk"
    assert candidate_decisions["error-explanation"]["decision"] == "abstain_retain"
    assert candidate_decisions["annotated-references"]["decision"] == "abstain_retain"
    assert candidate_audit["candidate_policy_used"] is True

    try:
        evaluate_quality_retention([rows[-1]], {"quality_score_threshold": 0.5})
    except RuntimeError as error:
        assert "score" in str(error).lower()
    else:
        raise AssertionError("Quality retention must reject scalar-score configuration.")

    try:
        QualityRetentionDecision(
            decision="reject",
            chunk_uid="invalid",
            policy_scope_route="common_all_routes",
            routing_precondition=RoutingPreconditionTrace(
                status="unknown",
                confidence="none",
                routes=("unknown",),
                router_version="fixture-router-v1",
            ),
            evaluated_policy_ids=(),
            non_trigger_boundary="fixture",
            evidence="fixture",
            original_text_sha256="a" * 64,
            policy_artifact_sha256="b" * 64,
            token_delta_proxy=-1,
        )
    except QualityRetentionContractError as error:
        assert "Reject decisions require" in str(error)
    else:
        raise AssertionError("A reject without rule evidence must be unrepresentable.")

    print("[quality-retention] explicit reject evidence and abstain-retain boundary: pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
