from __future__ import annotations

import hashlib
import re
from pathlib import Path


EXPLICIT_GENERATED_ARTIFACT_REASON = "explicit_generated_artifact"
LICENSE_COMMENT_ONLY_REASON = "license_comment_only_chunk"
EMPTY_HTML_SHELL_REASON = "empty_html_shell"
WEB_CHROME_ONLY_REASON = "explicit_web_chrome_only_chunk"
ERROR_NAVIGATION_ONLY_REASON = "explicit_error_navigation_only_chunk"
URL_DIRECTORY_ONLY_REASON = "url_directory_only_chunk"

POLICY_IDS = {
    "explicit_generated_artifact": "stage_b_explicit_generated_artifact",
    "license_comment_only_chunk": "stage_b_license_comment_only",
    "empty_html_shell": "stage_b_empty_html_shell",
    "web_chrome_only_chunk": "stage_b_web_chrome_only_chunk",
    "explicit_error_navigation_only_chunk_candidate": (
        "stage_c_explicit_error_navigation_only_candidate"
    ),
    "url_directory_only_chunk_candidate": "stage_c_url_directory_only_candidate",
}
POLICY_VERSIONS = {
    POLICY_IDS["explicit_generated_artifact"]: "1.0.0",
    POLICY_IDS["license_comment_only_chunk"]: "1.0.0",
    POLICY_IDS["empty_html_shell"]: "1.0.0",
    POLICY_IDS["web_chrome_only_chunk"]: "1.0.0",
    POLICY_IDS["explicit_error_navigation_only_chunk_candidate"]: "0.1.0",
    POLICY_IDS["url_directory_only_chunk_candidate"]: "0.1.0",
}

FIXTURE_REGISTRY = "validation/fixtures/quality_retention_v2_cases.json"
POLICY_FIXTURES = {
    POLICY_IDS["explicit_generated_artifact"]: (
        f"{FIXTURE_REGISTRY}#generated_artifact_trigger",
        f"{FIXTURE_REGISTRY}#generated_artifact_false_positive",
    ),
    POLICY_IDS["license_comment_only_chunk"]: (
        f"{FIXTURE_REGISTRY}#license_only_trigger",
        f"{FIXTURE_REGISTRY}#license_only_false_positive",
    ),
    POLICY_IDS["empty_html_shell"]: (
        f"{FIXTURE_REGISTRY}#empty_html_trigger",
        f"{FIXTURE_REGISTRY}#empty_html_false_positive",
    ),
    POLICY_IDS["web_chrome_only_chunk"]: (
        f"{FIXTURE_REGISTRY}#web_chrome_trigger",
        f"{FIXTURE_REGISTRY}#web_chrome_false_positive",
    ),
    POLICY_IDS["explicit_error_navigation_only_chunk_candidate"]: (
        f"{FIXTURE_REGISTRY}#error_navigation_trigger",
        f"{FIXTURE_REGISTRY}#error_navigation_false_positive",
    ),
    POLICY_IDS["url_directory_only_chunk_candidate"]: (
        f"{FIXTURE_REGISTRY}#url_directory_trigger",
        f"{FIXTURE_REGISTRY}#url_directory_false_positive",
    ),
}

POLICY_ARTIFACT_PATH = Path(__file__).resolve().parent / "configs" / "policy_cards.json"
POLICY_ARTIFACT_SHA256 = hashlib.sha256(POLICY_ARTIFACT_PATH.read_bytes()).hexdigest()
CANDIDATE_QUALITY_RULE_KEYS = frozenset(
    {
        "explicit_error_navigation_only_chunk_candidate",
        "url_directory_only_chunk_candidate",
    }
)
FORBIDDEN_SCORE_KEYS = frozenset(
    {
        "quality_score",
        "quality_score_threshold",
        "weighted_quality_score",
        "minimum_quality",
        "target_retention_fraction",
    }
)

TOKEN_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
EXPLICIT_GENERATED_ARTIFACT_RE = re.compile(
    r"^\s*(?:[#/;*\-]+\s*)?(?:\b(?:generated by|auto[- ]?generated|automatically generated)\b[^\n]{0,160}\bdo not edit\b|\bdo not edit\b[^\n]{0,160}\b(?:generated by|auto[- ]?generated|automatically generated)\b)",
    re.IGNORECASE | re.MULTILINE,
)
COMMENT_LINE_RE = re.compile(r"^\s*(?:#|//|/\*|\*|<!--|--|\*/)")
LICENSE_COMMENT_MARKER_RE = re.compile(
    r"\b(?:copyright|spdx-license-identifier|licensed under|all rights reserved|permission is hereby granted)\b",
    re.IGNORECASE,
)
HTML_DOCUMENT_RE = re.compile(
    r"^\s*(?:<!doctype\s+html\s*>)?\s*<html\b[^>]*>.*</html>\s*$",
    re.IGNORECASE | re.DOTALL,
)
HTML_TAG_RE = re.compile(r"<[^>]+>")
URL_LINE_RE = re.compile(r"^(?:https?://|www\.)\S+$", re.IGNORECASE)
WEB_CHROME_CONTROL_LINES = frozenset(
    {
        "cookie preferences",
        "accept all",
        "reject all",
        "manage preferences",
        "privacy policy",
        "terms of service",
    }
)
ERROR_MARKER_LINES = frozenset(
    {"404 page not found", "page not found", "nothing found for", "access denied", "403 forbidden"}
)
NAVIGATION_LINES = frozenset(
    {"home", "about", "contact", "search", "menu", "previous", "next", "back to home"}
)


def is_license_comment_only(text: str) -> bool:
    lines = [line for line in text.splitlines() if line.strip()]
    return bool(lines) and all(COMMENT_LINE_RE.match(line) for line in lines) and bool(
        LICENSE_COMMENT_MARKER_RE.search("\n".join(lines))
    )


def is_empty_html_shell(text: str) -> bool:
    if not HTML_DOCUMENT_RE.fullmatch(text):
        return False
    return not TOKEN_RE.search(HTML_TAG_RE.sub(" ", text))


def is_web_chrome_only(text: str) -> bool:
    lines = [" ".join(line.casefold().split()) for line in text.splitlines() if line.strip()]
    return len(lines) >= 4 and all(line in WEB_CHROME_CONTROL_LINES for line in lines)


def is_error_navigation_only(text: str) -> bool:
    lines = [" ".join(line.casefold().split()) for line in text.splitlines() if line.strip()]
    allowed = ERROR_MARKER_LINES | NAVIGATION_LINES
    return (
        bool(lines)
        and all(line in allowed for line in lines)
        and any(line in ERROR_MARKER_LINES for line in lines)
        and sum(line in NAVIGATION_LINES for line in lines) >= 3
    )


def is_url_directory_only(text: str) -> bool:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return len(lines) >= 5 and all(URL_LINE_RE.fullmatch(line) for line in lines)
