@echo off
setlocal EnableExtensions

:: Tuned low-memory profile for Windows click-run
set PHASE1_DEVICE=auto
set PHASE1_CUDA_DEVICE=0
set PHASE1_USE_GPU=1
set PHASE1_DOMAIN_BATCH_SIZE=256
set PHASE1_MAX_BATCHES=2
set PHASE1_INDEX_MAX_BATCHES=2
set PHASE1_TFIDF_MAX_FEATURES=3000
set PHASE1_BUILD_TFIDF_MATRIX=1
set PHASE1_STORE_DOC_TEXTS=1
set PHASE1_ENABLE_MINHASH=1
set PHASE1_QUERY_CACHE_LIMIT=1200
set PHASE1_NGRAM_CACHE_LIMIT=2500
set PHASE1_SEMANTIC_CANDIDATE_LIMIT=300
set PHASE1_NGRAM_CANDIDATE_LIMIT=120
set PHASE1_SKIP_REDUNDANCY=0
set PHASE1_SKIP_PERPLEXITY=0

python "%~dp0run_phase1_lowmem.py"
if %ERRORLEVEL% neq 0 exit /b %ERRORLEVEL%
